-- SENTENCIA PARA ENCONTRAR LOS USUARIOS QUE HAN HECHO AL MENOS UNA RESERVA EN EL RANGO DE FECHAS PARA UN ALOJAMIENTO
SELECT * 
FROM (SELECT RESERVAS.ID AS IDRESERVA, COBRO, ESTADO, FECHAINICIO, FECHAFIN, FECHAREALIZACION, IDCLIENTE, COLECTIVA, CLIENTES.ID, CEDULA, NOMBRE, EDAD, TELEFONO
        FROM RESERVAS INNER JOIN CLIENTES ON CLIENTES.ID = RESERVAS.IDCLIENTE 
        WHERE FECHAREALIZACION >='01/01/2017' AND FECHAREALIZACION <= '31/12/2017') T1
     INNER JOIN        
     (SELECT *
        FROM OFERTASRESERVAS INNER JOIN OFERTAS ON OFERTAS.ID = OFERTASRESERVAS.IDOFERTA
        WHERE OFERTAS.IDALOJAMIENTO = 614 AND OFERTAS.IDOPERADOR = 37291) T2
     ON T1.IDRESERVA = T2.IDRESERVA;
        
                
-- SENTENCIA PARA ENCONTRAR LOS USUARIOS QUE NO HAN HECHO NI UNA RESERVA EN ESAS FECHAS--              
SELECT *
FROM CLIENTES, RESERVAS 
WHERE CLIENTES.id NOT IN 
                  (SELECT IDCLIENTE 
                    FROM (SELECT RESERVAS.ID AS IDRESERVA, COBRO, ESTADO, FECHAINICIO, FECHAFIN, FECHAREALIZACION, IDCLIENTE, COLECTIVA, CLIENTES.ID, CEDULA, NOMBRE, EDAD, TELEFONO
                            FROM RESERVAS INNER JOIN CLIENTES ON CLIENTES.ID = RESERVAS.IDCLIENTE 
                            WHERE FECHAREALIZACION >='01/01/2018' AND FECHAREALIZACION <= '31/12/2018') T1
                         INNER JOIN        
                         (SELECT *
                            FROM OFERTASRESERVAS INNER JOIN OFERTAS ON OFERTAS.ID = OFERTASRESERVAS.IDOFERTA
                            WHERE OFERTAS.IDALOJAMIENTO = 4) T2
                         ON T1.IDRESERVA = T2.IDRESERVA
                  ) 
AND CLIENTES.ID = RESERVAS.IDCLIENTE;
                
-- SENTENCIA PARA ENCONTRAR LA OFERTA CON MAYOR OCUPACION--
SELECT * FROM 
    (SELECT COUNT(OFRS.IDRESERVA), OFERTAS.ID, OFERTAS.IDOPERADOR, OFERTAS.IDALOJAMIENTO, OFERTAS.COSTO, OFERTAS.ESTADO, OFERTAS.NOMBRE
    FROM (SELECT IDOFERTA, IDRESERVA, COBRO, ESTADO, TO_CHAR(FECHAINICIO, 'WW') SEMANAINICIO, TO_CHAR(FECHAFIN, 'WW') SEMANAFIN, IDCLIENTE, COLECTIVA
            FROM OFERTASRESERVAS INNER JOIN RESERVAS ON RESERVAS.ID = IDRESERVA
            WHERE TO_CHAR(FECHAINICIO, 'WW') <15 AND ((TO_CHAR(FECHAFIN, 'WW') >15) OR (TO_CHAR(FECHAFIN, 'WW') < TO_CHAR(FECHAINICIO, 'WW')))) OFRS
        , OFERTAS
    WHERE OFRS.IDOFERTA = OFERTAS.ID 
    group by OFERTAS.ID, OFERTAS.IDOPERADOR, OFERTAS.IDALOJAMIENTO, OFERTAS.COSTO, OFERTAS.ESTADO, OFERTAS.NOMBRE
    order by COUNT(OFRS.IDRESERVA) DESC), ALOJAMIENTOS 
WHERE rownum =1 and IDALOJAMIENTO = ALOJAMIENTOS.ID;

-- SENTENCIA PARA ENCONTRAR LAS OFERTAS CON MENOR OCUPACION--
SELECT * FROM 
    (SELECT COUNT(OFRS.IDRESERVA), OFERTAS.ID, OFERTAS.IDOPERADOR, OFERTAS.IDALOJAMIENTO, OFERTAS.COSTO, OFERTAS.ESTADO, OFERTAS.NOMBRE
    FROM (SELECT IDOFERTA, IDRESERVA, COBRO, ESTADO, TO_CHAR(FECHAINICIO, 'WW') SEMANAINICIO, TO_CHAR(FECHAFIN, 'WW') SEMANAFIN, IDCLIENTE, COLECTIVA
            FROM OFERTASRESERVAS INNER JOIN RESERVAS ON RESERVAS.ID = IDRESERVA
            WHERE TO_CHAR(FECHAINICIO, 'WW') <15 AND ((TO_CHAR(FECHAFIN, 'WW') >15) OR (TO_CHAR(FECHAFIN, 'WW') < TO_CHAR(FECHAINICIO, 'WW')))) OFRS
        , OFERTAS
    WHERE OFRS.IDOFERTA = OFERTAS.ID 
    group by OFERTAS.ID, OFERTAS.IDOPERADOR, OFERTAS.IDALOJAMIENTO, OFERTAS.COSTO, OFERTAS.ESTADO, OFERTAS.NOMBRE
    order by COUNT(OFRS.IDRESERVA) ASC), ALOJAMIENTOS 
WHERE  IDALOJAMIENTO = ALOJAMIENTOS.ID;

-- SENTENCIA PARA ENCONTRAR LOS OPERADORES MÁS SOLICITADOS--
SELECT * FROM 
    (SELECT COUNT(OFRS.IDRESERVA), OFERTAS.IDOPERADOR
    FROM    (SELECT IDOFERTA, IDRESERVA, COBRO, ESTADO, TO_CHAR(FECHAINICIO, 'WW') SEMANAINICIO, TO_CHAR(FECHAFIN, 'WW') SEMANAFIN, IDCLIENTE, COLECTIVA
            FROM OFERTASRESERVAS INNER JOIN RESERVAS ON RESERVAS.ID = IDRESERVA
            WHERE TO_CHAR(FECHAINICIO, 'WW') <15 AND ((TO_CHAR(FECHAFIN, 'WW') >15) OR (TO_CHAR(FECHAFIN, 'WW') < TO_CHAR(FECHAINICIO, 'WW'))))
            OFRS
            , OFERTAS
    WHERE OFRS.IDOFERTA = OFERTAS.ID 
    group by OFERTAS.IDOPERADOR
    order by COUNT(OFRS.IDRESERVA) DESC), OPERADORES 
WHERE  IDOPERADOR = OPERADORES.ID; 

-- SENTENCIA PARA ENCONTRAR LOS OPERADORES MENOS SOLICITADOS-- revisar
SELECT *
FROM(SELECT * FROM 
        (SELECT COUNT(OFRS.IDRESERVA) AS NUMRESERVAS, OFERTAS.IDOPERADOR
        FROM (SELECT IDOFERTA, IDRESERVA, COBRO, ESTADO, TO_CHAR(FECHAINICIO, 'WW') SEMANAINICIO, TO_CHAR(FECHAFIN, 'WW') SEMANAFIN, IDCLIENTE, COLECTIVA
                FROM OFERTASRESERVAS INNER JOIN RESERVAS ON RESERVAS.ID = IDRESERVA
                WHERE TO_CHAR(FECHAINICIO, 'WW') <15 AND ((TO_CHAR(FECHAFIN, 'WW') >15) OR (TO_CHAR(FECHAFIN, 'WW') < TO_CHAR(FECHAINICIO, 'WW'))))
                OFRS
            , OFERTAS
        WHERE OFRS.IDOFERTA = OFERTAS.ID 
        group by OFERTAS.IDOPERADOR), OPERADORES 
    WHERE IDOPERADOR = OPERADORES.ID
    order by NUMRESERVAS ASC)
WHERE ROWNUM =1;

-- SENTENCIA PARA CONSULTAR LOS BUENOS CLIENTES A PARTIR DE LA UNIÓN ENTRE LOS QUE HACEN --

----COMPROBAR LAS RESERVAS QUE HA HECHO EN EL ÚLTIMO AÑO----
select *
from (SELECT IDCLIENTE, (TO_CHAR(FECHAREALIZACION-365, 'MM'))
        FROM RESERVAS 
        WHERE FECHAREALIZACION >= (TO_CHAR(SYSDATE-365, 'DD-MM-YYYY')) 
        group by IDCLIENTE, FECHAREALIZACION, (TO_CHAR(FECHAREALIZACION-365, 'MM'))
        ORDER BY IDCLIENTE, FECHAREALIZACION) inner join clientes on idcliente = clientes.id;
            
        
----HALLAR LOS CLIENTES QUE HACEN RESERVAS CARAS----
------HALLAR LAS RESERVAS CARAS Y QUIÉNES LAS HAN HECHO
        SELECT count(*), clientes.id as cliente
        FROM CLIENTES INNER JOIN RESERVAS ON CLIENTES.ID = RESERVAS.IDCLIENTE
        WHERE RESERVAS.COBRO/(FECHAFIN-FECHAINICIO) >= 150
        GROUP BY clientes.id;
------VERIFICAR QUE TODAS LAS RESERVAS DE LOS CLIENTES SEAN CARAS
        SELECT * 
        FROM(SELECT COUNT(*) AS RESERVASTOTALES, CLIENTES.ID AS CLIENTE, CLIENTES.CEDULA, CLIENTES.EDAD, CLIENTES.NOMBRE, CLIENTES.TELEFONO
                FROM CLIENTES INNER JOIN RESERVAS ON CLIENTES.ID = RESERVAS.IDCLIENTE 
                GROUP BY CLIENTES.ID, CLIENTES.CEDULA, CLIENTES.EDAD, CLIENTES.NOMBRE, CLIENTES.TELEFONO)
            NATURAL INNER JOIN 
            ( SELECT count(*) AS RESERVASCARAS, clientes.id as cliente, CLIENTES.CEDULA, CLIENTES.EDAD, CLIENTES.NOMBRE, CLIENTES.TELEFONO
                FROM CLIENTES INNER JOIN RESERVAS ON CLIENTES.ID = RESERVAS.IDCLIENTE
                WHERE RESERVAS.COBRO/(FECHAFIN-FECHAINICIO) >= 150
                GROUP BY clientes.id, CLIENTES.CEDULA, CLIENTES.EDAD, CLIENTES.NOMBRE, CLIENTES.TELEFONO)
        WHERE RESERVASTOTALES <= 2* RESERVASCARAS;
--------------------------------------------------------


----HALLAR LOS CLIENTES QUE RESERVAN SUITES----
------HALLAR LAS RESERVAS DE SUITES Y QUIÉNES LAS HAN HECHO
SELECT COUNT(IDRESERVA), IDCLIENTE, CEDULA, NOMBRE, EDAD, TELEFONO 
FROM    (SELECT * FROM CLIENTES INNER JOIN (SELECT ID AS RESERVA, IDCLIENTE FROM RESERVAS) ON CLIENTES.ID = IDCLIENTE)
    INNER JOIN
        (SELECT * FROM OFERTASRESERVAS 
                    INNER JOIN
                        (SELECT CATEGORIA, NUMERO, UBICACION, IDHOTEL, IDALOJAMIENTO, OFERTAS.ID AS IDOFERTA1
                                FROM HABSHOTEL INNER JOIN OFERTAS ON HABSHOTEL.ID = OFERTAS.IDALOJAMIENTO
                                WHERE CATEGORIA = 'SUITE')
          ON IDOFERTA = IDOFERTA1) 
    ON IDRESERVA = RESERVA 
group by IDCLIENTE, CEDULA, NOMBRE, EDAD, TELEFONO;
    
---- VERIFICAR QUE TODAS SEAN SUITES----------
 SELECT * 
        FROM(SELECT COUNT(*) AS RESERVASTOTALES, CLIENTES.ID AS CLIENTE, CLIENTES.CEDULA, CLIENTES.EDAD, CLIENTES.NOMBRE, CLIENTES.TELEFONO
                FROM CLIENTES INNER JOIN RESERVAS ON CLIENTES.ID = RESERVAS.IDCLIENTE 
                GROUP BY CLIENTES.ID, CLIENTES.CEDULA, CLIENTES.EDAD, CLIENTES.NOMBRE, CLIENTES.TELEFONO) T1,
            (SELECT COUNT(IDRESERVA) AS RESERVASSUITE, IDCLIENTE, CEDULA, NOMBRE, EDAD, TELEFONO 
                FROM    (SELECT * FROM CLIENTES INNER JOIN (SELECT ID AS RESERVA, IDCLIENTE FROM RESERVAS) ON CLIENTES.ID = IDCLIENTE)
                    INNER JOIN
                        (SELECT * FROM OFERTASRESERVAS 
                                    INNER JOIN
                                        (SELECT CATEGORIA, NUMERO, UBICACION, IDHOTEL, IDALOJAMIENTO, OFERTAS.ID AS IDOFERTA1
                                                FROM HABSHOTEL INNER JOIN OFERTAS ON HABSHOTEL.ID = OFERTAS.IDALOJAMIENTO
                                                WHERE CATEGORIA = 'SUITE')
                          ON IDOFERTA = IDOFERTA1) 
                    ON IDRESERVA = RESERVA 
                group by IDCLIENTE, CEDULA, NOMBRE, EDAD, TELEFONO) T2
WHERE T1.CLIENTE = T2.IDCLIENTE AND RESERVASTOTALES = RESERVASSUITE;
--------------------------------------------------------
