drop table habitaciones ;
drop table habsuniv ;
drop table habshotel;
drop table vdascomunidad;
drop table apartamentos;
drop table servicios;
drop table reservas;
drop table ofertas;
drop table alojamientos;
drop table personascom;
drop table personasnats;
drop table hostales;
drop table viviendasunivs;
drop table hoteles;
drop table responsables;
drop table operadores;
drop table clientes;
drop table usuarios;